name: poc_sentry_go_router
description: Tracking platforms library.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: 3.10.2

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^7.1.1 
  intl: ^0.17.0
  sentry_flutter: ^7.6.3
  

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
